Добавил кнопку "Проект по умолчанию"
inngvar/imanagestuff pull request #31
Opened 2020-10-26 09:43 UTC by Q-new

2020-10-27 11:48 UTC, inngvar commented on package.json
> +    "prettier": "2.0.5",
Версия понизилась, не надо так

2020-10-27 11:48 UTC, inngvar commented on package.json
> +    "generator-jhipster": "6.10.1",
Версия понизилась, не надо так

2020-10-27 11:51 UTC, inngvar commented on src/main/webapp/app/entities/member/member.tsx
> -  useEffect(() => {
А этот блок точно доложен быть удалён?

2020-10-27 11:53 UTC, inngvar requested changes

2020-10-27 11:53 UTC, inngvar commented on src/test/javascript/spec/app/entities/member/member-reducer.spec.ts
> -        {
А почему тут методы удалились?

2020-10-27 12:14 UTC, Q-new commented on package.json
> +    "generator-jhipster": "6.10.1",
Я не хотел package.json коммитить, видимо случайно зацепил

2020-10-27 12:15 UTC, Q-new commented on package.json
> +    "prettier": "2.0.5",
Я не хотел package.json коммитить, видимо случайно зацепил

2020-10-27 12:16 UTC, Q-new commented on src/main/webapp/app/entities/member/member.tsx
> -  useEffect(() => {
Это сделал генератор, не я. Но без него вроде все работает. По крайней мере я не заметил что это на что-то влияет.

2020-10-27 12:17 UTC, Q-new commented on src/test/javascript/spec/app/entities/member/member-reducer.spec.ts
> -        {
Здесь я тоже не трогал, генератор JHipster я решил не исправлять

2020-10-27 14:22 UTC, inngvar commented on package.json
> +    "prettier": "2.0.5",
думаю надо попроаваить...

2020-10-27 15:10 UTC, inngvar commented
Надпись у кнопки надо сократить.  просто оставить "По умолчанию"

2020-10-28 06:59 UTC, Q-new commented
Поправил package.json, перенес кнопку в другой компонент для правильно отображения

2020-10-28 07:20 UTC, merged